#-------------------------------
# General Site Settings

title: Sandra Krle
description: Frontend developer portfolio
email: sandra.krlle@gmail.com

menu:
- {name: About Me, url: '#about'}
- {name: Work, url: '#work'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section


seo:
  description: 'juniour frontend developer portfolio'

#-------------------------------
# Google Analytics Section


google-analytics-ua: UA-78144734-1

#-------------------------------
# About Section


blurb: >
  **Sandra Krle's the name, frontend's the game.**
  I’m a Junior Frontend Developer based in Stockholm, Sweden. 
  I taught myself how to HTML, CSS and JavaScript.
  Then I did few internships at some really cools start-ups who taught me even more.
  Now I seek me a job. Preferably for juniors who are really fast and awesome at learning.


#-------------------------------
# Work Section

projects:
- {name: Professional experience, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: What I look for, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Personal stuff, folder: 'proj-3', file: 'work/proj-3.html'}


#-------------------------------
# Contact Section

social:
- {icon: 'linkedin', link: 'https://se.linkedin.com/in/sandrakrle'}
