#-------------------------------
# General Site Settings

title: Sandra Krle
description: Frontend developer
email: sandra dot krlle at gmail

menu:
- {name: About Me, url: '#about'}
- {name: Work, url: '#work'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section


seo:
  description: 'Frontend Developer'

#-------------------------------
# Google Analytics Section


google-analytics-ua: UA-78144734-1

#-------------------------------
# About Section


blurb: >
  **Sandra Krle's the name, frontend's the game.**<br/>
  I’m a Junior/Intermediate Frontend Developer currently based in Visby, Sweden.<br/>
  In 2015 I taught myself how to write JavaScript.<br/>
  Today, I work in a very big and important swedish company.<br/>
  React is my choice of weapon.

#-------------------------------
# Work Section

projects:
- {name: Professional experience, folder: 'proj-1', file: 'work/proj-1/proj-1.html'}
- {name: What I look for, folder: 'proj-2', file: 'work/proj-2/proj-2.html'}
- {name: Personal stuff, folder: 'proj-3', file: 'work/proj-3/proj-3.html'}


#-------------------------------
# Contact Section

social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/sandrakrle'}
- {icon: 'github', link: 'https://github.com/SandraKrle'}
